### ISSUE TITLE
Using a custom anchor with an empty fragment from multiple sections gives a "Multiple elements have the same ID" error

### ISSUE THREAD

**Issue by jyasskin** [speced/bikeshed#2531]
```bikeshed
<pre class='metadata'>
Title: Your Spec Title
Shortname: your-spec
Level: 1
Status: w3c/UD
Group: WGNAMEORWHATEVER
Repository: org/repo-name
URL: http://example.com/url-this-spec-will-live-at
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract: A short description of your spec, one or two sentences.
Complain About: accidental-2119 yes, missing-example-ids yes
Markup Shorthands: markdown yes, css no
</pre>

<pre class="anchors">
urlPrefix: https://tools.ietf.org/html/rfc8941; spec: rfc8941
    type: dfn
        text: structured header; url: #
</pre>

[=Structured Header=]

Section {#section}
----------------------------

[=Structured Header=]
```

Error:
```
LINE ~28: Multiple elements have the same ID '60d1f67e0'.
Deduping, but this ID may not be stable across revisions.
```

**Comment by tabatkins** [comment]
Okay it's extremely weird that this happens *solely* with an empty anchor; changing that to `#foo` avoids the error. Investigating...

**Comment by tabatkins** [comment]
Ah, figured it out. Two overlapping bugs:

* Because I used the fragment of the href to auto-gen the ID on `a` elements, I was testing for the fragment and just not generating an ID at all if it lacked on (or, as it turns out, if it had one but it was empty). Fixed now; these now generate the ID `ref-for-something`. (And everything generated in this step gets deduped properly.)
* If a link didn't previously have an ID, I generated one via a different process while adding dfn panels. For Reasons I can't rely on the normal deduping here, so I instead hashed some stuff together in a way that should be unique per panel, and appended an increasing number to keep them unique from each other. But this number was accidentally reset per section. Fixed now to constantly increase for a given dfn panel.
