### ISSUE TITLE
Unexpected error: Unknown metadata key "Dark Mode"

### ISSUE THREAD

**Issue by MattiasBuelens** [speced/bikeshed#2561]
The Streams standard fails to build because of an unexpected Bikeshed error. This happens both locally and [on our CI](https://github.com/whatwg/streams/actions/runs/5082538123/jobs/9202930894).

## Steps to reproduce

1. Run `bikeshed update`
1. Clone the Streams standard at the latest commit: whatwg/streams@cf7670a934ce228e2560e981a0d94e8e4201f217
1. Run `make local`

## Expected results

The specification builds normally.

## Actual results

Bikeshed reports an error about an unknown metadata key.
```
$ make local
bikeshed spec index.bs index.html --md-Text-Macro="COMMIT-SHA LOCAL COPY"
FATAL ERROR: Unknown metadata key "Dark Mode". Prefix custom keys with "!".
 ✘  Did not generate, due to fatal errors
Makefile:19: recipe for target 'local' failed
make: *** [local] Error 2
```
However, the Streams standard does not define such a metadata key, see [index.bs](https://github.com/whatwg/streams/blob/cf7670a934ce228e2560e981a0d94e8e4201f217/index.bs#L1-L13).

**Comment by tabatkins** [comment]
Yup, apologies, I forget that since the datafiles aren't versioned, I do need to line up pip releases with these sorts of additions. (I refactored how Bikeshed handles darkmode styles to make it actually work sensibly, and now they can be toggled on or off more directly.)

The 3.12.0 release, cut about an hour ago, fixes the issue afaict.
