### ISSUE TITLE
Relax the PyPI package version requirements

### ISSUE THREAD

**Issue by Mick235711** [speced/bikeshed#2616]
Currently, the pip package `bikeshed` requires the following packages:
```
aiofiles==23.1.0
aiohttp==3.8.4
alive-progress==3.0.1
attrs==22.1.0
certifi==2022.12.7
cssselect==1.2.0
html5lib==1.1
isodate==0.6.1
json-home-client==1.1.1
lxml==4.9.2
Pillow==9.5.0
Pygments==2.15.1
requests==2.29.0
result==0.8.0
tenacity==8.2.2
widlparser==1.1.3
```
This approach (require exact version of every required package) seems uncommon for PyPI packages, since most packages describe their requirements as minimum version requirements. For example, `pandas` requires:
```
numpy>=1.23.2
python-dateutil>=2.8.2
pytz>=2020.1
tzdata>=2022.1
```
Requiring exact version of packages also causes many problems for bikeshed to coexist with other PyPI packages, since it is very possible that the required versions are not the latest ones, and other package may require a new version. For a real-world example, currently bikeshed 3.14.3 requires attrs==22.1.0, but latest version of jsonschema (4.18.4) requires attrs>=22.2.0. If both are >= this will not be a conflict.

Is it possible to change all requirements to >= or is there a specific reason for requiring exact versions in the Pipfile? Thanks a lot for answering in advance!

**Comment by tabatkins** [comment]
Those are exact versions now because the requirements file is autogenerated from my Pipfile.lock, which captures exact versions by design. This does cause conflicts if you install Bikeshed globally (which was previously the recommended method), but `pipx` (the recommended install method now) now makes it trivial to to install and manage things from pip in their own environments so they can't clash with each other in this precise way. Alternately, you can use whatever environment manager you're already using, such as `pipenv`.

I apologize that this is probably a change from how you were using Bikeshed before, but global installations really are dangerous, both between installed packages and, often, for system integrity itself (as OSes increasingly end up using some amount of Python themselves, and upgrading the packages they depend on can break things). The tools for managing local environments took a long time to finally become reasonably usable, but `pipx` is just *so good* now, I can't recommend it highly enough.

So, assuming you previously installed Bikeshed globally via pip, I recommend uninstalling it and using pipx to reinstall it - [the docs should have sufficient instructions](https://speced.github.io/bikeshed/#install-pipx).

**Comment by Mick235711** [comment]
Thanks for the explanation. Now I understand the design and will definitely try the new method.
