### ISSUE TITLE
CR requires Deadline now?

### ISSUE THREAD

**Issue by tabatkins** [speced/bikeshed#2644]
Currently only FPWD and PR are marked as "needing Deadline" in Bikeshed. However, it appears that CRs now require it as well; Specberus appears to demand it. Also, the CSSWG status.include file has deadline text, but for some reason the macro is marked as optional. (And the line predates me splitting the boilerplates out to their own project, so archaeology will be annoying.)

I need to investigate what the actual requirements are here and get things synced up.

**Comment by svgeesus** [comment]
Yes, CR needs a deadline for comments (even though everyone accepts comments at any time). This is because we now get patent policy protection from CR onwards, not just from Rec; which means that publishing a CR Snapshot also triggers an AC review, and the [Process Document says](https://www.w3.org/2023/Process-20231103/#ACReviewStart) that AC reviews must state the deadline for the review period

> **5.7.1. Start of a Review Period**

> Each [Advisory Committee review](https://www.w3.org/2023/Process-20231103/#advisory-committee-review) period begins with a Call for Review from the [Team](https://www.w3.org/2023/Process-20231103/#team) to the [Advisory Committee](https://www.w3.org/2023/Process-20231103/#advisory-committee). The Call for Review describes the proposal, raises attention to deadlines, estimates when the decision will be available, and includes other practical information. Each Member organization may send one review, which must be returned by its [Advisory Committee representative](https://www.w3.org/2023/Process-20231103/#advisory-committee-representative).

**Comment by tabatkins** [comment]
Okay, thanks.
