### ISSUE TITLE
Character reference being detected in code block 

### ISSUE THREAD

**Issue by backkem** [speced/bikeshed#2732]
I have a build failing on a file that didn't change:
* [Last green build](https://github.com/WICG/local-peer-to-peer/actions/runs/7118409347/job/19381298439#step:3:468) (Bikeshed 3.14.5)
* [Failed build](https://github.com/WICG/local-peer-to-peer/actions/runs/7150465346/job/19473973067?pr=26#step:3:790) (Bikeshed [4.0.0](https://github.com/WICG/local-peer-to-peer/actions/runs/7150465346/job/19473973067?pr=26#step:3:756))

It seems the piece of code `&result` is being interpreted as a HTML Character reference. I wonder if this may be a regression or if I should somehow escape this character instead.

**Comment by tabatkins** [comment]
That error is correct - that's technically a [parse error in HTML](https://html.spec.whatwg.org/multipage/parsing.html#named-character-reference-state).

(Bikeshed is slightly more strict than HTML itself here; in HTML, if the `&foo` isn't actually on [the list of char ref names](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references), it's technically valid in HTML. That's a really fragile sort of error, given the sheer size and unpredictability of that list, and the fact that prefixes count (like, `&copyright` is caught because `"copy" is on the list, generating a parse error and the text "©right"). So Bikeshed errs slightly stricter, but much more predictably, and flags anything which looks like a character reference.)

Yeah, you can either escape the ampersand (`&amp;`) or switch your `pre` to `xmp` (tho that won't work in your case, since you have markup there).
