### ISSUE TITLE
Bikeshed may generate an empty row in a property definition table

### ISSUE THREAD

**Issue by tidoust** [speced/bikeshed#2774]
The property definition of `font-style` in CSS Fonts 4 ends with an HTML comment in the source:
https://github.com/w3c/csswg-drafts/blob/main/css-fonts-4/Overview.bs#L1115

That comment is not new. What's new is that Bikeshed now generates an empty row at the end of the definition table when it processes that block, see:
https://drafts.csswg.org/css-fonts-4/#font-style-prop

I believe that's the only occurrence across specs. At least that's the only spec on which Reffy crashed because it did not know what to do with an empty row ;). The spec could perhaps simply be updated to move the comment out of the `<pre>` tag.

Via https://github.com/w3c/webref/issues/1130

**Comment by tabatkins** [comment]
Fixed in 761dd74f0, I'll cut a release in a few.

**Comment by tabatkins** [comment]
And yeah, previously I did an early pass, before almost any other text processing, to remove comments from the source. This was unsafe, since it would strip them from, say, the contents of an `<xmp>`, or within a markdown code block. Now that I parse comments along with everything else, I can properly leave them alone in any context where I'm parsing as text rather than HTML. That means the comment now persists until I do propdef block parsing, and I happily generate a table row for it. And I purposely don't escape the text when I build the HTML, here, so you can insert markup and it'll work normally, so that ends up just stretching the comment across the `th` and into the `td`.

Anyway, I now strip comments from the lines when parsing def blocks.
