### ISSUE TITLE
"Suggest an edit" link is sometimes wrong.

### ISSUE THREAD

**Issue by svgeesus** [speced/bikeshed#2784]
The recently published CSS Viewport spec was just corrected after publication because the "Suggest an edit" link was 404:

```html
 <dd><a href="https://github.com/w3c/csswg-drafts/blob/main/css-viewport-1/Overview.bs">GitHub Editor</a>
```

changed to       
        
```html
    <dd><a href="https://github.com/w3c/csswg-drafts/blob/main/css-viewport/Overview.bs">GitHub Editor</a>
```

I wasn't sure what to fix in the .bs source so that it gets generated correctly. Is it because the directory name does not have a level?

**Comment by tabatkins** [comment]
That line comes from the boilerplate: <https://github.com/speced/bikeshed-boilerplate/blob/main/boilerplate/csswg/defaults.include#L6>

It uses the `[VSHORTNAME]` macro, because that's the pattern we use for our folder names. Looks like the `css-viewport` folder is, indeed, named incorrectly, and should have `-1` appended to it.

If I make the change right now it'll make the published spec wrong *again*, so I'll leave it to you to coordinate the changes. ^_^
